server:
  port: 8090
  error:
    include-message: always

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dvt

management:
  endpoints:
    web:
      exposure:
        include: "*"

data-validation-tool:

  default-column-data-cache-config:
    cache-type: IN-MEMORY
    eviction-strategy: FIFO
    max-number-of-elements-in-cache: 1000

  datasources:
    TEST_IN_MEMORY_DATASOURCE:
      cache-config:
        cache-type: IN-MEMORY
        eviction-strategy: FIFO
        max-number-of-elements-in-cache: 1000
    JSON_DATASOURCE:
      cache-config:
        cache-type: REDIS
        eviction-strategy: FIFO
        max-number-of-elements-in-cache: 1000

  redis-config:
    host: localhost
    port: 6379